# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E7E1DE
background         #272726
cursor             #A6A57B

active_tab_foreground     #272726
active_tab_background     #E7E1DE
inactive_tab_foreground   #E7E1DE
inactive_tab_background   #272726

active_border_color   #E7E1DE
inactive_border_color #272726
bell_border_color     #173E62

color0      #4D4D4B
color1		#173E62
color2		#4C4F11
color3		#505218
color4		#606B7C
color5		#787059
color6		#8C7F7A
color7		#D4CCC8
color8		#948E8C
color9		#1E5382
color10		#666917
color11		#6B6D20
color12		#808FA6
color13		#A09577
color14		#BAA9A2
color15		#D4CCC8
